export interface Employee {
    userName: string;                   // Tên nhân viên
    userCode: string;                   // Mã nhân viên
    gender: string;                     // Giới tính
    genderView?: string;                // Giới tính View
    dateOfBirth: string;                // Ngày/tháng/năm sinh
    phone: string;                      // Số điện thoại
    address: string;                    // Địa chỉ
    email: string;                      // Email
    identityCard: string;               // CCCD
    status: string;                     // Trạng thái
    statusView?: string;                // Trạng thái View
    position: string;                   // Chức vụ
    positionView?: string;              // Chức vụ View
    laborContract: string;              //  Mã hợp đồng lao động
    salary: string;                     // Mức lương
    dateEnd: string;                    // gày nghỉ
    dateStart: string;                  // Ngày vào làm
} 

export interface SalartEmployee {
    userName: string;                   // Tên nhân viên
    userCode: string;                   // Mã nhân viên
    position: string;                   // Chức vụ
    positionView?: string;              // Chức vụ View
    salary: string;                     // Mức lương
    workDay: string;                    // Ngày công
    allowance: string;                  // Phụ cấp 
    bonus: string;                      // Thưởng
    punish: string;                     // Phạt
    advance: string;                    // Tạm ứng
    actuallyReceived: string;           // Thực nhận
    status: string;                     // Trạng thái
    statusView?: string;                // Trạng thái View
    dateOfReceipt: string;              // Ngày nhận
    phone?: string;
    email?: string;
    address?: string;
}

export interface Account {
    name: string;
    email: string;
    positionView: string;
}

//Báo cáo danh sách tài khoản
export const accountFakeData: Account[] = [
    {
        name: 'Phạm Tuyết Nhung',
        email: 'nhung@hanoisky.com',
        positionView: 'Quản lý'
    },
    {
        name: 'Vũ Hồng han',
        email: 'hanvu@hanoisky.com',
        positionView: 'Quản lý'
    }, 
    {
        name: 'Lê Thanh Hiếu',
        email: 'hieu@hanoidky.com',
        positionView: 'Giám đốc'
    }
]

//Quản lý lương theo tháng
export const employeeFakeData:Employee[] = [
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "3000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "4000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "5000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "5000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "7000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "8000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "9000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "900000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
    {
        userName: "Nguyễn Văn A",
        userCode: "NV001",
        gender: "0",
        dateOfBirth: "01/01/1990",
        phone: "0987654321",
        address: "123 Đường ABC, Quận XYZ, Hà Nội",
        email: "nguyenvana@example.com",
        identityCard: "123456789",
        status: "working",
        position: "director",
        laborContract: "LD001",
        salary: "10000000",
        dateEnd: "01/01/2022",
        dateStart: "01/01/2010"
    },
    {
        userName: "Trần Thị B",
        userCode: "NV002",
        gender: "1",
        dateOfBirth: "02/02/1995",
        phone: "0123456789",
        address: "456 Đường XYZ, Quận ABC, Hà Nội",
        email: "tranthib@example.com",
        identityCard: "987654321",
        status: "onLeave",
        position: "manager",
        laborContract: "LD002",
        salary: "15000000",
        dateEnd: "",
        dateStart: "01/01/2010"
    },
]

//Thống kê danh sách lương nhân viên theo mức lương
export const salartEmployee: SalartEmployee[] = [
    {
        userName: "Nguyễn Nhựt Trường", 
        userCode: "NV00",
        position: "director",     
        positionView: "Giám đốc", 
        salary: "40000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Mai Việt Anh", 
        userCode: "NV00",
        position: "manager",     
        positionView: "Quản lý", 
        salary: "30000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Trần Thanh Trúc", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Đoàn Minh Tú", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Hoàng Bùi Sơn", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "3000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Văn Linh", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "5000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Thanh Sơn", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "4000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Nhật Trường", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "6000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Bạch Hồng Yến", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "7000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nay Quyền", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "8000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Phan Văn Quốc Hùng", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Thị Bích Ngọc", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Mạnh Chiến", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "900000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Nhựt Cường", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Đinh Tiến Thành", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Kiều Mỹ", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "9000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Lê Minh Đạt", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Văn Hiền", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "3000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Vương Minh Tú", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "3000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Hồ Văn Tùng", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "3000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Thám", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "3000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Thị Mộng Tuyết", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Huy Khánh", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Thị Xuân Nữ", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Võ Công Toàn", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lý Thị Kim Ngân", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Phan Thị Thúy Ngọc", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Hồng Phúc", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Minh Trường", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Thành Trí", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Dương Anh Chí", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Thuận Phương", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lâm Hữu Đạt", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Ngọc Hoàng Hưng", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lê Văn Hiền", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Thị Quỳnh Anh", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Văn Linh", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Thị Bích Ngọc", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nay Quyền", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Trần Gia Bảo", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lý Bích Châu", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Phan Văn Sơn", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Kim Nguyên", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Huỳnh Như Vĩnh Phát", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Tiêu Thị Thùy Uyên", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Nguyễn Huy Khánh", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Vũ Minh Tuyến", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Vũ Văn Hoàng", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Lương Minh Duyên", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
    {
        userName: "Hoàng Bùi Sơn", 
        userCode: "NV00",
        position: "employee",     
        positionView: "Nhân viên", 
        salary: "10000000",  
        workDay: "22",    
        allowance: "400000",  
        bonus: "1000000", 
        punish: "0",  
        advance: "0",            
        actuallyReceived: "",    
        status: "working",           
        statusView: "Đang làm việc",           
        dateOfReceipt: "7/5/2024",
        email: "demo@gmail.com",
        phone: "0936476123",
        address: "Ha Noi"        
    },
]

